spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    jpa:
      open-in-view: false
    hibernate:
      ddl-auto: update   # на старте удобно для разработки
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port: 8080
